---
- name: Install and init vsftpd ftp-server
  hosts: all
  roles:
    - vsftpd-install

#  become: yes
#  gather_facts: no
#  vars:
#    ftp_name: vsftpd

#  tasks:
#    - name: "Install {{ ftp_name }} FTP server"
#      yum:
#        name: "{{ ftp_name }}"
#        state: present

#    - name: "Start service {{ apache_name }}"
#      service:
#        name: "{{ apache_name }}"
#        state: started
#        enabled: yes


#    - name: Enable firewalld
#      service: name=firewalld state=started enabled=yes

#    - name: Permit traffic for http service
#      firewalld:
#        port: 80/tcp
#        permanent: yes
#        state: enabled
#        immediate: yes
