---
- name: Create users
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
  - users.yaml

  tasks:
    - name: "Create users"
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
        comment: "{{ item.comment }}"
        state: present
      no_log: true
      loop: "{{ users }}"
