---
- name: Uninstall Apache web-server
  hosts: all
  become: yes
  gather_facts: no
  vars:
    apache_name: httpd

  tasks:
    - name: "Uninstall {{ apache_name }}"
      yum:
        name: "{{ apache_name }}"
        state: absent

    - name: Delete start
      file:
        name: /var/www/html/index.html
        state: absent

    - name: Enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Deny traffic for http service
      firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled
        immediate: yes
