---
- block:
  - name: "Install {{ ftp_name }} FTP server"
    yum:
      name: "{{ ftp_name }}"
      state: present

# Too many troubles for standart approach
#  - name: "Set httpd_can_network_connect flag on and keep it persistent across reboots"
#    ansible.posix.seboolean:
#      name: ftpd_anon_write
#      state: yes
#      persistent: yes

  - name: Check SELinux context
    command:
      cmd: "getsebool {{ selinux_context_name }}"
    register: selinux_context
    changed_when: false

  - name: Change SElinux context
    command:
      cmd: "setsebool -P {{ selinux_context_name }} on"
    when: selinux_context.stdout.find('off') != -1  

  - name: Create root folder
    file:
      path: /var/ftp/pub
      state: directory
      mode: "555"
      owner: ftp
      group: ftp

  - name: Create upload folder
    file:
      path: /var/ftp/pub/upload
      state: directory
      mode: "777"
      owner: ftp
      group: ftp

  - name: Copy FTP config
    ansible.builtin.template:
      src: vsftpd.conf.j2
      dest: "{{ vsftpd_conf }}"
    notify: Reload FTP service

  - name: Enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Permit traffic for ftp service
    firewalld:
#      service: "ftp" 
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - "20-21"
      - "30000-50000"

#  - name: Permit traffic for ftp service
#    firewalld:
#      port: "30000-50000/tcp"
#      permanent: yes
#      state: enabled
#      immediate: yes


  become: yes
