---
- block:
  - name: "Install {{ ftp_name }} FTP server"
    yum:
      name: "{{ ftp_name }}"
      state: present

# Too many troubles for standart approach
#  - name: "Set httpd_can_network_connect flag on and keep it persistent across reboots"
#    ansible.posix.seboolean:
#      name: ftpd_anon_write
#      state: yes
#      persistent: yes

  - name: Check SELinux context ftpd_full_access
    command:
      cmd: "getsebool {{ selinux_ftpd_full_access }}"
    register: selinux_context_ftpd_full_access
    changed_when: false

  - name: Change SElinux context ftpd_full_access 
    command:
      cmd: "setsebool -P {{ selinux_ftpd_full_access }} on"
    when: selinux_context_ftpd_full_access.stdout.find('off') != -1  

  - name: Check SELinux context ftpd_anon_write
    command:
      cmd: "getsebool {{ selinux_ftpd_anon_write }}"
    register: selinux_context_ftpd_anon_write 
    changed_when: false

  - name: Change SElinux context ftpd_anon_write 
    command:
      cmd: "setsebool -P {{ selinux_ftpd_anon_write }} on"
    when: selinux_context_ftpd_anon_write .stdout.find('off') != -1


  - name: Create root folder
    file:
      path: "{{ anon_root }}"
      state: directory
      mode: "555"
      owner: ftp
      group: ftp

  - name: Create upload folder
    file:
      path: "{{ anon_root }}/{{ anon_write_subfolder }}"
      state: directory
      mode: "777"
      owner: ftp
      group: ftp

  - name: Copy FTP config
    ansible.builtin.template:
      src: vsftpd.conf.j2
      dest: "{{ vsftpd_conf }}"
    notify: Reload FTP service

  - name: Enable firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Permit traffic for ftp service
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - "20-21"
      - "{{ pasv_min_port }}-{{ pasv_max_port }}"

  become: yes
